language: ruby

os:
  - linux
  - osx

rvm:
  - 3.2
  - 3.1
  - 3.0
  - 2.7 # Current stable
  - 2.6 # Alpine 3.11
  - 2.5 # Debian stable (buster), Ubuntu
  - 2.1 # Minimum supported version (Debian oldoldstable (jessie))

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: ruby-head
  exclude:
    - os: osx
      rvm: ruby-head
    - os: osx
      rvm: 2.1

notifications:
  email: false

install:
  - gem install bundler -v '< 2'
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec gem build transmission-rss.gemspec
  - bundle exec rake
